# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1egz_qubHvNYNmHDPc_ZQFHsFJm0agFMF
"""

pip install openai pyPDF2

!pip install -q groq PyPDF2 sentence-transformers scikit-learn

import PyPDF2
from groq import Groq
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# ==========================
# GROQ API KEY
# ==========================
client = Groq(api_key="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")

# ==========================
# MODEL
# ==========================
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

# ==========================
# READ PDF
# ==========================
def read_pdf(file):
    text = ""
    with open(file, "rb") as f:
        reader = PyPDF2.PdfReader(f)

        for page in reader.pages:
            page_text = page.extract_text()

            if page_text:
                text += page_text + "\n"

    return text

# ==========================
# SPLIT INTO CHUNKS
# ==========================
def chunk_text(text, chunk_size=500):
    words = text.split()
    chunks = []

    for i in range(0, len(words), chunk_size):
        chunks.append(" ".join(words[i:i+chunk_size]))

    return chunks

book = read_pdf("/content/review874-1.pdf")

chunks = chunk_text(book)

print("Creating embeddings...")

chunk_embeddings = embedding_model.encode(chunks)

print("Done!")

# ==========================
# SEARCH
# ==========================
def retrieve(question, top_k=3):

    question_embedding = embedding_model.encode([question])

    scores = cosine_similarity(question_embedding, chunk_embeddings)[0]

    best = np.argsort(scores)[-top_k:][::-1]

    return "\n\n".join(chunks[i] for i in best)

# ==========================
# CHAT LOOP
# ==========================
while True:

    question = input("\nYou: ")

    if question.lower() == "exit":
        break

    context = retrieve(question)

    prompt = f"""
You are an expert tutor.

Answer ONLY from the context.

If the answer is missing, reply:

Not in PDF

Context:

{context}

Question:

{question}
"""

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[
            {
                "role":"user",
                "content":prompt
            }
        ],
        temperature=0,
        max_tokens=300
    )

    print("\nBot:", response.choices[0].message.content)